version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: AWS-Deployment/Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    networks:
      - portfolio-network
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: portfolio-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-network

  redis:
    image: redis:alpine
    container_name: portfolio-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - portfolio-network

volumes:
  mysql_data:
    driver: local

networks:
  portfolio-network:
    driver: bridge
